export const playerMotion = {
  speed: 0,
  analog: 0,
  accel: 0,
  turnRate: 0,
  controlLocked: true,
  distanceWalked: 0,
  walkCycle: 0,
  walkWeight: 0,
  x: 0,
  z: 1.55,
  yaw: Math.PI,
  faceYaw: null as number | null,
  flinch: 0,
  flashX: 0,
  flashY: 1.34,
  flashZ: 0,
  flashReady: false,
}
